FROM ubuntu:yakkety

RUN noint="DEBIAN_FRONTEND=noninteractive" \
	&& norec="--no-install-recommends" \
	&& apt-get update \
	&& $noint apt-get install -y $norec openssl curl ca-certificates \
	&& curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash \
	&& $noint apt-get install -y $norec git-lfs

RUN useradd --uid $UID -ms /bin/bash $USER

USER $USER

CMD /bin/bash

EXPOSE $PORTS
VOLUME [$VOLUMES]

