FROM debian:stable

RUN noint="DEBIAN_FRONTEND=noninteractive" \
	norec="--no-install-recommends" \
	apt-get update \
	&& $noint apt-get install -y $norec openssl curl ca-certificates vim sudo \
	&& curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash \
	&& $noint apt-get install -y $norec --allow-unauthenticated git-lfs

RUN for gid in $GROUPS ; do addgroup --system --gid $gid group$gid ; done

# RUN grouplist="$GROUPS" \
# 	useradd --uid $UID --gid $GID -G "$(echo ${grouplist// /,})" -M -b /host/home -s /bin/bash $USER
RUN grouplist="$GROUPS" \
	useradd --uid $UID --gid $GID -p "" -m -b /home -s /bin/bash $USER \
	&& usermod -a -G "$(echo ${grouplist// /,})" $USER

COPY wait.sh /
RUN chmod 755 /wait.sh

RUN echo "$USER ALL=(ALL:ALL) ALL" >> /etc/sudoers

USER $USER

# COPY bashrc /home/$USER/.bashrc
# RUN chmod 755 /home/$USER/.bashrc

EXPOSE $PORTS
VOLUME [$VOLUMES]

CMD ["/wait.sh"]

